# Generated by Django 5.0.4 on 2024-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image_alter_product_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
    ]
