# Generated by Django 5.0.4 on 2024-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(default='To Rate', max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
