# Generated by Django 5.0.6 on 2024-07-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rating_status_alter_rating_description_and_more'),
        ('transaction', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
    ]
