# Generated by Django 5.0.6 on 2024-08-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rating_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='transaction',
        ),
    ]
