# Generated by Django 5.0.4 on 2024-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
