# Generated by Django 5.0.6 on 2024-08-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='products_to_rate',
            field=models.TextField(null=True),
        ),
    ]
