# Generated by Django 5.0.4 on 2024-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.AddField(
            model_name='cart',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
